name: Install
on: [push, pull_request]
jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']
        phpunit-versions: ['latest']
        apache2: ['2.4']
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          service apache2 start
          service --status-all
          curl http://localhost
          

        
